"""init"

Revision ID: 489e671fa219
Revises: 
Create Date: 2025-03-11 23:42:42.048962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '489e671fa219'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('SERVICE1', 'SERVICE2', 'SERVICE3', 'SERVICE4', name='serviceplantype'), nullable=False),
    sa.Column('is_active', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='servicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    # ### end Alembic commands ###
